# Generated by Django 4.1.5 on 2023-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_caretaker_address_caretaker_city_caretaker_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_caretaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
